name: 'Noni Art & Design'
favicon: null
layout_spectrum: 0.4276605632621795
typography_spectrum: 0.35559943318367004
title: 'Contemporary Indigenous Australian Art & Design, Created For You'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#101318'
    - '#ffffff'
    - '#84312d'
    - '#ae585d'
    - '#d2d2d2'
  brandStrength: 0.375
  lightness: 0.25
  saturation: 0.3300289094913751
  rhythmicContrast: 0.18015897762961686
purpose: []
