name: 'Noni Art & Design'
favicon: null
layout_spectrum: 1
typography_spectrum: 0.31788
title: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#22231e'
    - '#6492f0'
    - '#54cf00'
    - '#fdf306'
  brandStrength: 0.5
  lightness: 0.25
  saturation: 0.3300289094913751
  rhythmicContrast: 0.18015897762961686
purpose: []
