name: 'Noni Art & Design'
favicon: null
layout_spectrum: 0
typography_spectrum: 0.46748
title: Noni - Art and Design
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#00001c'
    - '#816f87'
    - '#ffeed1'
    - '#700934'
    - '#f0917e'
  brandStrength: 0.5
  lightness: 0.4375
  saturation: 0.875
  rhythmicContrast: 0.25
purpose: []
