name: 'Noni Art & Design'
favicon: null
layout_spectrum: 0.24624
typography_spectrum: 0.32268
title: 'Noni, Art & Design'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#22231e'
    - '#6492f0'
    - '#54cf00'
    - '#fdf306'
  brandStrength: 0
  lightness: 0.4375
  saturation: 0.875
  rhythmicContrast: 0.5
purpose: []
